/** @format */

import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';

import './globals.css';
import { Analytics } from '@vercel/analytics/next';
import { BlurHeader } from '@/components/ui/Header';

export const metadata: Metadata = {
	title: 'CopyMe',
	// description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${GeistSans.className} ${GeistMono.className} antialiased`}>
				<BlurHeader />
				{children}
				<Analytics />
			</body>
		</html>
	);
}
