version: '3.8'

networks: 
  backend_net:
    driver: bridge
  tools-net:
    driver: bridge
  mongo-compose-network:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    user: "${MY_UID}:${MY_GID}"
    volumes:
      - ./.mongodb:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    restart: always
    networks:
      - backend_net
      - mongo-compose-network
    command: mongod --auth --bind_ip_all --bind_ip 0.0.0.0

  copyme-backend:
    container_name: copyme-backend
    build:
      context: ./copy-me_backend
      dockerfile: Dockerfile
    
    ports:
      - "3000:${COPYME_BACKEND_PORT}" 
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${COPYME_BACKEND_PORT}
      - MONGO_URI=${MONGO_URI}/copymedb?${MONGO_ARG}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
    restart: always
    networks:
      - backend_net