gender: 'men'
phases:
  - name: 'shot_position'
    angles:
      hip: { ref: 158.89, tolerance: 6.16 }
      knee: { ref: 116.7, tolerance: 7.4 }
      ankle: { ref: 108.39, tolerance: 10.58 }
      elbow: { ref: 90, tolerance: 5 }
  - name: 'shot_release'
    angles:
      hip: { ref: 158.89, tolerance: 6.16 }
      knee: { ref: 116.7, tolerance: 7.4 }
      ankle: { ref: 108.39, tolerance: 10.58 }
      elbow: { ref: 90, tolerance: 5 }
  - name: 'shot_followthrough'
    angles:
      hip: { ref: 158.89, tolerance: 6.16 }
      knee: { ref: 116.7, tolerance: 7.4 }
      ankle: { ref: 108.39, tolerance: 10.58 }
      elbow: { ref: 90, tolerance: 5 }
