name: Mirror all branches to org repo

on:
  push:
    branches:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    environment: token
    steps:
      - name: Checkout all branches
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add mirror remote and push
        env:
          MIRROR_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git remote add mirror https://x-access-token:${MIRROR_TOKEN}@github.com/EpitechPromo2026/G-EIP-700-RUN-7-1-eip-lucas.arnassalom.git
          git push mirror --all
          git push mirror --tags
